#!groovy

// Generated by IBM TransformationAdvisor
// Mon Apr 29 21:08:28 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}