#!groovy

// Generated by IBM TransformationAdvisor
// Thu Apr 25 15:41:27 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'defaultapplication'
    mvnCommands = '--version'
    test='false'
}