#!groovy

// Generated by IBM TransformationAdvisor
// Tue May 07 20:45:17 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}